# Generated by Django 3.0.8 on 2021-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190330_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpost1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=60)),
                ('pic', models.ImageField(upload_to='post')),
                ('attachement', models.FileField(upload_to='post')),
            ],
        ),
        migrations.CreateModel(
            name='Registerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
    ]
