# Generated by Django 3.0.5 on 2022-04-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_addpost1_registerform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
