# Generated by Django 3.0.5 on 2022-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220411_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
